<?php

return [
    ['url' => 'https://gontor.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unida.gontor.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://ui.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unair.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://ugm.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://itb.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://ipb.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://its.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://undip.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://uns.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unpad.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://ub.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://www.usu.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unp.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://um.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://uho.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://uinsa.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://uinjkt.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://uin-suka.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],

    ['url' => 'https://telkomuniversity.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://binus.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unpar.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://umn.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://ums.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://www.umy.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://uad.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://amikom.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://gunadarma.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://trisakti.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],

    ['url' => 'https://mercubuana.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unpam.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unisma.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unsoed.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://www.polinema.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://polban.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://polines.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://pnb.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],

    ['url' => 'https://stis.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://stikom.edu', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://stikom-bali.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://stiki.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],

    ['url' => 'https://universitaspertamina.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://president.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://ut.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://myut.ut.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://admisi-sia.ut.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://tmk.ut.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://untan.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],

    ['url' => 'https://untirta.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://untag-sby.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://untag-smd.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://ukdw.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://uksw.edu', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],

    ['url' => 'https://widyatama.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://widyagama.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unmul.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unsri.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unib.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],

    ['url' => 'https://web.upri.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://untad.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unram.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
    ['url' => 'https://unud.ac.id', 'uptime_check_enabled' => true, 'certificate_check_enabled' => true, 'is_public' => true],
];
