<?php

return [
    [
        'url' => 'https://syofyanzuhad.dev',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://www.google.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://facebook.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://x.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://instagram.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://linkedin.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://youtube.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://reddit.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://github.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://stackoverflow.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://medium.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://dev.to',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://chatgpt.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://openai.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://claude.ai',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://perplexity.ai',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://grok.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://bing.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://yahoo.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://duckduckgo.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://baidu.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://yandex.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://naver.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://seznam.cz',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://ask.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://wolframalpha.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://quora.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://wikipedia.org',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://amazon.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://ebay.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://aliexpress.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://etsy.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://craigslist.org',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://walmart.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://target.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://bestbuy.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://costco.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://homeDepot.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://lowes.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://target.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://aldi.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://lidl.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://traderjoes.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
    [
        'url' => 'https://wholefoodsmarket.com',
        'uptime_check_enabled' => true,
        'certificate_check_enabled' => true,
        'is_public' => true,
    ],
];
