<script setup lang="ts">
import { cn } from '@/lib/utils';
import {
    Activity,
    AlertCircle,
    AlertTriangle,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowUpNarrowWide,
    Box,
    CalendarClock,
    ChartBar,
    ChartLine,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsLeft,
    ChevronsRight,
    CircleAlert,
    CircleCheck,
    CircleHelp,
    CircleMinus,
    CircleX,
    Clock,
    Code,
    Columns2,
    Copy,
    Cpu,
    Database,
    Download,
    ExternalLink,
    Eye,
    Facebook,
    FileJson,
    FileText,
    Github,
    Globe,
    GripVertical,
    HardDrive,
    House,
    Inbox,
    Info,
    Layers,
    LayoutGrid,
    Link,
    Linkedin,
    List,
    Loader,
    Loader2,
    Lock,
    Mail,
    Maximize,
    MemoryStick,
    MessageCircle,
    Minimize,
    Monitor,
    Moon,
    Plus,
    Radio,
    RefreshCw,
    Search,
    SearchX,
    Send,
    Server,
    Settings,
    Share2,
    Shield,
    ShieldAlert,
    ShieldCheck,
    ShieldOff,
    Sun,
    Tag,
    Terminal,
    TrendingUp,
    Twitter,
    Upload,
    X,
    Zap,
    Gauge,
    Sparkles,
} from 'lucide-vue-next';
import { computed } from 'vue';

const registry: Record<string, any> = {
    activity: Activity,
    alertCircle: AlertCircle,
    'alert-circle': AlertCircle,
    alertTriangle: AlertTriangle,
    'alert-triangle': AlertTriangle,
    arrowDown: ArrowDown,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    arrowUp: ArrowUp,
    sortAsc: ArrowUpNarrowWide,
    calendarClock: CalendarClock,
    chartBar: ChartBar,
    chartLine: ChartLine,
    check: Check,
    checkCircle: CheckCircle,
    'check-circle': CheckCircle,
    chevronDown: ChevronDown,
    'chevron-down': ChevronDown,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    chevronsLeft: ChevronsLeft,
    chevronsRight: ChevronsRight,
    circleAlert: CircleAlert,
    circleCheck: CircleCheck,
    circleHelp: CircleHelp,
    helpCircle: CircleHelp,
    circleMinus: CircleMinus,
    'minus-circle': CircleMinus,
    circleX: CircleX,
    xCircle: CircleX,
    clock: Clock,
    code: Code,
    columns: Columns2,
    'columns-2': Columns2,
    copy: Copy,
    cpu: Cpu,
    download: Download,
    externalLink: ExternalLink,
    'external-link': ExternalLink,
    eye: Eye,
    facebook: Facebook,
    fileJson: FileJson,
    fileText: FileText,
    github: Github,
    globe: Globe,
    gripVertical: GripVertical,
    hardDrive: HardDrive,
    home: House,
    house: House,
    inbox: Inbox,
    info: Info,
    layoutGrid: LayoutGrid,
    grid: LayoutGrid,
    'grid-2x2': LayoutGrid,
    link: Link,
    linkedin: Linkedin,
    list: List,
    loader: Loader,
    loader2: Loader2,
    'loader-2': Loader2,
    lock: Lock,
    mail: Mail,
    maximize: Maximize,
    memoryStick: MemoryStick,
    messageCircle: MessageCircle,
    minimize: Minimize,
    monitor: Monitor,
    moon: Moon,
    plus: Plus,
    refreshCw: RefreshCw,
    search: Search,
    searchX: SearchX,
    server: Server,
    settings: Settings,
    share2: Share2,
    shield: Shield,
    shieldAlert: ShieldAlert,
    shieldCheck: ShieldCheck,
    shieldOff: ShieldOff,
    sun: Sun,
    tag: Tag,
    trendingUp: TrendingUp,
    twitter: Twitter,
    upload: Upload,
    x: X,
    zap: Zap,
    gauge: Gauge,
    sparkles: Sparkles,
    box: Box,
    layers: Layers,
    radio: Radio,
    send: Send,
    database: Database,
    terminal: Terminal,
    // heroicons compat — map to closest lucide
    'heroicons:plus': Plus,
    'heroicons:exclamation-triangle': AlertTriangle,
    'heroicons:arrow-path': RefreshCw,
    'heroicons:chevron-down': ChevronDown,
};

interface Props {
    name: string;
    class?: any;
    size?: number | string;
    color?: string;
    strokeWidth?: number | string;
}

const props = withDefaults(defineProps<Props>(), {
    class: '',
    size: 16,
    strokeWidth: 2,
});

const className = computed(() => cn('h-4 w-4', props.class));
const icon = computed(() => registry[props.name] ?? registry[props.name.charAt(0).toUpperCase() + props.name.slice(1)] ?? null);
</script>

<template>
    <component :is="icon" v-if="icon" :class="className" :size="size" :stroke-width="strokeWidth" :color="color" />
</template>
