<?php

return [
    'https://gontor.ac.id',
    'https://unida.gontor.ac.id',
    'https://ui.ac.id',
    'https://unair.ac.id',
    'https://ugm.ac.id',
    'https://itb.ac.id',
    'https://ipb.ac.id',
    'https://its.ac.id',
    'https://undip.ac.id',
    'https://uns.ac.id',
    'https://unpad.ac.id',
    'https://ub.ac.id',
    'https://www.usu.ac.id',
    'https://unp.ac.id',
    'https://um.ac.id',
    'https://uho.ac.id',
    'https://uinsa.ac.id',
    'https://uinjkt.ac.id',
    'https://uin-suka.ac.id',

    'https://telkomuniversity.ac.id',
    'https://binus.ac.id',
    'https://unpar.ac.id',
    'https://umn.ac.id',
    'https://ums.ac.id',
    'https://www.umy.ac.id',
    'https://uad.ac.id',
    'https://amikom.ac.id',
    'https://gunadarma.ac.id',
    'https://trisakti.ac.id',

    'https://mercubuana.ac.id',
    'https://unpam.ac.id',
    'https://unisma.ac.id',
    'https://unsoed.ac.id',
    'https://www.polinema.ac.id',
    'https://polban.ac.id',
    'https://polines.ac.id',
    'https://pnb.ac.id',

    'https://stis.ac.id',
    'https://stikom.edu',
    'https://stikom-bali.ac.id',
    'https://stiki.ac.id',

    'https://universitaspertamina.ac.id',
    'https://president.ac.id',
    'https://ut.ac.id',
    'https://myut.ut.ac.id',
    'https://admisi-sia.ut.ac.id',
    'https://elearning.ut.ac.id',
    'https://tmk.ut.ac.id',
    'https://untan.ac.id',

    'https://untirta.ac.id',
    'https://untag-sby.ac.id',
    'https://untag-smd.ac.id',
    'https://ukdw.ac.id',
    'https://uksw.edu',

    'https://widyatama.ac.id',
    'https://widyagama.ac.id',
    'https://unmul.ac.id',
    'https://unsri.ac.id',
    'https://unib.ac.id',

    'https://web.upri.ac.id',
    'https://untad.ac.id',
    'https://unram.ac.id',
    'https://unud.ac.id',
];
