name: tests

on:
  push:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: pcov

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Build Assets
        run: npm run build

      - name: Tests (TIA)
        run: ./vendor/bin/pest --tia

      - name: Tests with coverage
        if: github.event_name == 'push'
        run: ./vendor/bin/pest --coverage --min=90 --coverage-clover=storage/coverage/coverage.xml

      - name: Show Coverage
        if: github.event_name == 'push'
        run: ls -lah ./storage/coverage

      - name: Upload Coverage
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./storage/coverage/coverage.xml
          flags: php
